### Simple logistic regression

In [1]:
# importing libraries
import sklearn as sk
from sklearn.datasets import load_diabetes, make_classification
import sklearn.linear_model as sk_lm
import sklearn.model_selection as sk_ms
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import sklearn.metrics as sk_mx
import seaborn as sns
# from sklearn.inspection import DecisionB/oundaryDisplay

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
# importing files for logistic regression workout
diab=load_diabetes()
X, Y = diab.data,diab.target

In [ ]:
# len(diab.data[0])
# diab
(1/0.54)*.4

In [ ]:
# encoding Y --> classification
y_class=(Y>np.mean(Y)).astype('int')
y_class.sum()/len(y_class)*100
y_class.sum()

In [ ]:
x_train,x_test,y_train,y_test=sk_ms.train_test_split(X,y_class,test_size=0.3,random_state=42)
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
lg_md=sk_lm.LogisticRegression()
lg_md.fit(x_train,y_train)
y_pred=cc.predict(x_test)
y_pred_prob=lg_md.predict_proba(x_test)
y_train_test=lg_md.predict(x_train)

In [ ]:
sk_mx.confusion_matrix(y_train,y_train_test)

In [ ]:
sk_mx.confusion_matrix(y_test,y_pred)

In [ ]:
data={'y_pred_class':y_pred, 'y_pred_prob2':y_pred_prob[:,1], 'y_pred_proba1':y_pred_prob[:,0]}
data1=pd.DataFrame(data)

In [ ]:
data1[data1['y_pred_class']==1].y_pred_prob2.min(),data1[data1['y_pred_class']==1].y_pred_prob2.max(),data1[data1['y_pred_class']==1].y_pred_prob2.mean(),data1[data1['y_pred_class']==1].y_pred_prob2.median()

In [ ]:
accuracy_test=sk_mx.accuracy_score(y_test,y_pred)
accuracy_train=sk_mx.accuracy_score(y_train,y_train_test)
print(accuracy_train,accuracy_test)

In [ ]:
sk_mx.confusion_matrix(y_test,y_pred)
y_pred.sum()


In [ ]:
c=lg_md.intercept_
m4=lg_md.coef_[0][2]
m8=lg_md.coef_[0][8]

def decision_boundary(x):
    return -(c+m4*x)/m8
dec_bnd=decision_boundary(x_test[:, 2])
x=np.linspace(x_test[:, 2].min(),x_test[:, 2].max(),len(dec_bnd))
# len(dec_bnd),len(x)
np.arange(x_test[:, 2].min(),x_test[:, 2].max())

In [ ]:

# Visuaintercept_the decision boundary with accuracy information
plt.figure(figsize=(8, 6))
sns.scatterplot(x=x_test[:, 2], y=x_test[:, 8], hue=y_test, color={
                0: 'blue', 1: 'red'}, marker='o')
plt.plot(x_test[:, 2],decision_boundary(x_test[:, 2]),ls="--",label="decision boundary",color="black")
plt.xlabel("BMI")
plt.ylabel("Age")
plt.title("Logistic Regression Decision Boundary\nAccuracy: {:.2f}%".format(
    accuracy_test * 100))
plt.legend(title="Diabetes", loc="upper right")
plt.grid()
plt.show()

#### Imbalanced dataset

In [ ]:
X, y = make_classification(n_samples=1000, n_features=20, n_informative=2,
                           n_redundant=10, weights=[0.995, 0.005], random_state=42)
X.shape, y.shape
y.mean()

In [ ]:
X_train, X_test, y_train, y_test = sk_ms.train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
lr_model = sk_lm.LogisticRegression(random_state=42)
lr_model.fit(X_train, y_train)
 
# Make predictions with the standard model
y_pred_lr = lr_model.predict(X_test)
y_pred_lr_prob=lr_model.predict_proba(X_test)[:,1]
 
# Evaluate the standard model
print("Logistic Regression:")
print(sk_mx.classification_report(y_test, y_pred_lr))
 
# Fit a weighted logistic regression model
weights = {0: 1, 1: 1000}  # Weight 10 for class 1 (minority class)
weighted_lr_model = sk_lm.LogisticRegression(random_state=42, class_weight=weights)
weighted_lr_model.fit(X_train, y_train)
 
# Make predictions with the weighted model
y_pred_weighted_lr = weighted_lr_model.predict(X_test)
y_pred_weighted_lr_prob=weighted_lr_model.predict_proba(X_test)[:,1]

im_data=pd.DataFrame({'actual':y_test,'pred_lr':y_pred_lr,'prob_lr': y_pred_lr_prob,'pred_wlr': y_pred_weighted_lr,'prob_wlr':y_pred_weighted_lr_prob})

# Evaluate the weighted model
print("Weighted Logistic Regression:")
print(sk_mx.classification_report(y_test, y_pred_weighted_lr))
accuracy_lr=sk_mx.accuracy_score(y_test,y_pred_lr)
accuracy_wlr=sk_mx.accuracy_score(y_test,y_pred_weighted_lr)

In [ ]:
print(im_data[im_data['pred_lr']==1].prob_lr.min(),im_data[im_data['actual']==1].prob_lr.max())
print(im_data[im_data['pred_wlr']==1].prob_wlr.min(),im_data[im_data['actual']==1].prob_wlr.max())

In [ ]:
# Visualize the decision boundary with accuracy information
plt.figure(figsize=(8, 6))
sns.scatterplot(x=X_test[:, 2], y=X_test[:, 8], hue=y_pred_lr, color={
                0: 'blue', 1: 'red'}, marker='o')
plt.xlabel("BMI")
plt.ylabel("Age")
plt.title("Logistic Regression Decision Boundary\nAccuracy: {:.2f}%".format(
    accuracy_lr * 100))
plt.legend(title="Diabetes", loc="upper right")
plt.show()

In [ ]:
# Visualize the decision boundary with accuracy information
plt.figure(figsize=(8, 6))
sns.scatterplot(x=X_test[:, 2], y=X_test[:, 8], hue=y_pred_weighted_lr, color={
                0: 'blue', 1: 'red'}, marker='o')
plt.xlabel("BMI")
plt.ylabel("Age")
plt.title("Logistic Regression Decision Boundary\nAccuracy: {:.2f}%".format(
    accuracy_wlr * 100))
plt.legend(title="Diabetes", loc="upper right")
plt.show()

In [ ]:
pd.DataFrame({'actual':y_test,'pred_lr':y_pred_lr,'prob_lr': y_pred_lr_prob,'pred_wlr': y_pred_weighted_lr,'prob_wlr':y_pred_weighted_lr_prob})

In [ ]:
# # Plot ROC Curve
# fpr, tpr, thresholds = roc_curve(y_test, y_pred_lr_prob)
# roc_auc = auc(fpr, tpr)
 
# plt.figure(figsize=(8, 6))
# plt.plot(fpr, tpr, color='darkorange', lw=2,
#          label=f'ROC Curve (AUC = {roc_auc:.2f})')
# plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random')
# plt.xlabel('False Positive Rate')
# plt.ylabel('True Positive Rate')
# plt.title('Receiver Operating Characteristic (ROC) Curve\nAccuracy: {:.2f}%'.format(
#     accuracy * 100))
# plt.legend(loc="lower right")
# plt.show()

In [ ]:
weighted_lr_model.intercept_[0]

In [ ]:
weighted_lr_model.coef_

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.tree import DecisionTreeClassifier
iris = load_iris()
feature_1, feature_2 = np.meshgrid(
    np.linspace(iris.data[:, 0].min(), iris.data[:, 0].max()),
    np.linspace(iris.data[:, 1].min(), iris.data[:, 1].max())
)
grid = np.vstack([feature_1.ravel(), feature_2.ravel()]).T
tree = DecisionTreeClassifier().fit(iris.data[:, :2], iris.target)
y_pred = np.reshape(tree.predict(grid), feature_1.shape)
display = DecisionBoundaryDisplay(
    xx0=feature_1, xx1=feature_2, response=y_pred
)
display.plot()

display.ax_.scatter(
    iris.data[:, 0], iris.data[:, 1], c=iris.target, edgecolor="black"
)

plt.show()

In [2]:
from itertools import product

In [51]:
arr = np.array(list(product([1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6], [1,2,3,4,5,6] ))).transpose()
arr[:3],arr[3:]

(array([[1, 1, 1, ..., 6, 6, 6],
        [1, 1, 1, ..., 6, 6, 6],
        [1, 1, 1, ..., 6, 6, 6]]),
 array([[1, 1, 1, ..., 6, 6, 6],
        [1, 2, 3, ..., 4, 5, 6]]))

In [28]:
pd.Series(np.max(arr[0].tolist())).value_counts()

6    1
dtype: int64

In [30]:
pd.Series(np.max(arr[:3],axis=0)).value_counts().sort_index()

1      36
2     252
3     684
4    1332
5    2196
6    3276
dtype: int64

In [32]:
np.max(arr[:3],axis=0)

array([1, 1, 1, ..., 6, 6, 6])

In [33]:
arr

array([[1, 1, 1, ..., 6, 6, 6],
       [1, 1, 1, ..., 6, 6, 6],
       [1, 1, 1, ..., 6, 6, 6],
       [1, 1, 1, ..., 6, 6, 6],
       [1, 2, 3, ..., 4, 5, 6]])